name: Build TIL

on:
  repository_dispatch:
    types: [sample_push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0
        path: main
    - name: Checkout til-db
      uses: actions/checkout@v2
      with:
        repository: mharty3/til-db
        path: til-db
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements.txt
    - name: Download til database unless REBUILD in commit message
      run: curl --fail -o main/build_til/til.db https://raw.githubusercontent.com/mharty3/til-db/main/til.db
      continue-on-error: true
    - name: Build TIL
      run: |-
        cd main
        python build_til/build_til.py --rewrite
        cat _pages/til.md
    - name: Commit and push if TIL changed
      run: |-
        cd main
        git diff
        git config --global user.email "til-bot@example.com"
        git config --global user.name "TIL-bot"
        git diff --quiet || (git add _pages/til.md && git add _til && git commit -m "Updated TIL")
        git push
